name: "Import youtube"
on: 
  workflow_dispatch
  push
      
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Clean Directory
        run: |
          rm -rf qt/*
          rm -rf sermon/*
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install

      - run: node youtube-import.js
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     commit_message: "[배포] Notion 변경 사항 저장"
      #     branch: main
      #     commit_user_name: importer-bot 🤖
      #     commit_user_email: actions@github.com
      #     commit_author: importer-bot 🤖 <actions@github.com>
 