name: "Import notion pages"
on:
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]
      
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Clean Directory
        run: |
          rm -rf _posts/introduction/*
          rm -rf _posts/ministry/*
          rm -rf _posts/bulletin/*
          rm -rf images/*
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install

      - run: node notion-import.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[배포] Notion 변경 사항 저장"
          branch: main
          commit_user_name: importer-bot 🤖
          commit_user_email: kmj4138@gmail.com
          commit_author: importer-bot 🤖 <kmj4138@gmail.com>
 